# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2447fee9f81b24aed2ad01d5d94be6859bcc1528285b9b35cc628837c7ee8195b9f237e899dff1cb4bba4ef5958b45b61a0f9930de5dde8f542dc237af96aea8

test:
  secret_key_base: 1b96deae1324d974d34401e6e50e3d1c287b7b609ff4de98feb80e9f1873966756b80ff2fc18379f15c5fb5c0e2a7eb4ebcc6943265b7e26fe5e2d5976694cbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
