source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails'
# Use sqlite3 as the database for Active Record
gem 'sqlite3-ruby'
group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'rspec-rails'
end
group :test do
  gem 'rspec'
  gem 'webrat'
end

